entur/lamassu

src/main/java/org/entur/lamassu/leader/entityupdater/VehiclesUpdater.java
src/main/java/org/entur/lamassu/leader/listener/delegates/VehicleListenerDelegate.java
src/main/java/org/entur/lamassu/service/impl/GeoSearchServiceImpl.java
src/test/java/org/entur/lamassu/leader/listener/delegates/VehicleListenerDelegateTest.java
src/test/java/org/entur/lamassu/service/GeoSearchServiceTest.java
src/test/java/org/entur/lamassu/stubs/VehicleCacheStub.java

Previously, the system id was postfixed to the vehicle id for the cache key, in order to provide efficient lookup during expiry event cleanup. However, this prevents simple lookup by id in the cache (as in #167) if you don't know which system the vehicle belongs to. This PR moves the burden to the expiry event handler to loop through all entries in the spatial index to find the right entry to expire. This needs to be properly tested.

Use vehicle id as cache key in vehicle cache

---

src/main/java/org/entur/lamassu/controller/GBFSFeedController.java
src/main/java/org/entur/lamassu/util/CacheUtil.java
src/test/java/org/entur/lamassu/util/CacheUtilTest.java

Some feeds are out of date, so the calculation would give a negative result. This sets the minimum to 0 + some refactoring.
Fixes #216

fix: max-age should not be less than 0

---

src/main/java/org/entur/lamassu/util/SpatialIndexIdUtil.java
src/test/java/org/entur/lamassu/util/SpatialIndexIdFilterTest.java

This PR partly addresses #250 (partly) by treating missing `station.vehicle_types_available` as empty arrays.
Note: it does not provide better loggging, but only fixes an ingestion exception with missing `vehicle_types_available`.
In consequence, no exceptions are logged for e.g. this feed configuration:
```yaml
lamassu:
providers:
- systemId: lime_zu
operatorId: LME:Operator:lime
operatorName: Lime
codespace: DKY
url: "https://data.lime.bike/api/partners/v2/gbfs/zug/gbfs.json"
language: en
```
and the following queries returned expected results:
http://localhost:8080/gbfs/lime_zu/gbfs
http://localhost:8080/gbfs/lime_zu/station_status
http://localhost:8080/gbfs/lime_zu/station_information
Before: Whitelabel Error page
After: gfbs/station_status/station_information is shown …

Handle missing vehicle_types_available gracefully

---

pom.xml

This PR adds jib-spring-boot-extension-maven to to prevent spring-boot-devtools from being packaged in docker image.
This fixes #266.

Exclude spring-boot-devtools from jib-built docker image

---

README.md
src/main/java/org/entur/lamassu/model/provider/Authentication.java

This PR adds the possibility to add a scope to the OAuth2 configuration.
This addition has been tested successfully with a feed from provider TIER.
Note: this PR requires the merge of https://github.com/entur/gbfs-loader-java/pull/118 and release of a new `gbfs-loader-java` version and a corresponding upgrade in `pom.xml`.

Add optional scope to outh2 configuration

---

src/main/java/org/entur/lamassu/leader/entityupdater/VehicleFilter.java
src/main/java/org/entur/lamassu/leader/entityupdater/VehiclesUpdater.java
src/test/java/org/entur/lamassu/leader/entityupdater/VehicleFilterTest.java

This PR changes VehicleFilter to not skip vehicles with their pricing_plan_id not set
Closes #396
A unit test to demonstrate this issue was added.
n.a.

fix: do not skip vehicles without pricing plan id (fixes #396)

---

src/main/java/org/entur/lamassu/metrics/MetricsService.java
src/test/java/org/entur/lamassu/metrics/MetricsServiceTest.java

Fixes issues with registering metrics. Metrics are registered once per combination of name and tags - subsequent calls are lost. It is required to keep counters for each combination, which gets hairy. This PR simplifies the setup, removes the file error metrics, and removes version and file tags.
Closes #438 
Unit tests were added to reproduce the problems and verify solution.

fix: metrics were not registered correctly, this simplifies the setup

---

src/main/java/org/entur/lamassu/controller/GBFSInternalV2FeedController.java
src/main/java/org/entur/lamassu/controller/GBFSV2FeedController.java
src/main/java/org/entur/lamassu/controller/GBFSV3FeedController.java
src/main/java/org/entur/lamassu/controller/UpstreamFeedNotYetAvailableException.java
src/test/java/org/entur/lamassu/controller/GBFSV2FeedControllerTest.java
src/test/java/org/entur/lamassu/controller/GBFSV3FeedControllerTest.java

This PR changes the 404 to an 503 http status code reply when a requested system feed it not found but it's system_id is configured. 
Closes #431 .
Manually verified.

Respond with status code 502 if configured feed not yet available

---

pom.xml

Both #466 and #450 should have bumped serialization version but I forgot. This PR bumps manually two steps for clarity.

Bump serialization version after two PRs that should have done it

---

src/main/java/org/entur/lamassu/leader/FeedUpdater.java
src/main/java/org/entur/lamassu/leader/entityupdater/EntityCachesUpdater.java
src/main/java/org/entur/lamassu/leader/entityupdater/GeofencingZonesUpdater.java
src/main/java/org/entur/lamassu/leader/entityupdater/StationsUpdater.java
src/main/java/org/entur/lamassu/leader/entityupdater/VehicleFilter.java
src/main/java/org/entur/lamassu/leader/entityupdater/VehiclesUpdater.java
src/main/java/org/entur/lamassu/mapper/entitymapper/GeofencingZonesMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/PricingPlanMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/RentalUrisMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/StationMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/SystemDiscoveryMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/SystemMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/VehicleMapper.java
src/main/java/org/entur/lamassu/mapper/entitymapper/VehicleTypeMapper.java
src/main/java/org/entur/lamassu/model/entities/VehicleTypeCapacity.java
src/main/resources/graphql/schema.graphqls
src/test/java/org/entur/lamassu/leader/entityupdater/VehicleFilterTest.java

Switching to GBFS v3 as the base for entity mapping enables us to expose new gbfs features in graphql api (see #412)
Closes #457 
There is decent automated test coverage for this change, but I've also done some manual testing with your production feeds.

Switch to v3 as base model for entity mapping

---

src/main/java/org/entur/lamassu/mapper/entitymapper/SystemDiscoveryMapper.java

During refactoring, a regression was introduced which generated v3beta urls for v2 system discovery. This PR fixes that regression by calling the correct method overload.

fix: incorrect urls generated for system discovery (v2)

---

.github/workflows/ci.yml
pom.xml

remotely related: #249
This PR configures Jib to build `linux/arm64` images, so one can run them natively on ARM machines, as documented [here](https://github.com/GoogleContainerTools/jib/tree/bb36a18a94fb0b7beb9203cf359bc88a95e038da/jib-maven-plugin#from-object).

CI: build & publish linux/arm64 images

---

src/main/java/org/entur/lamassu/mapper/entitymapper/VehicleMapper.java
src/main/java/org/entur/lamassu/mapper/feedmapper/v2/FreeBikeStatusFeedMapper.java
src/main/java/org/entur/lamassu/mapper/feedmapper/v3/VehicleStatusFeedMapper.java
src/test/java/org/entur/lamassu/mapper/feedmapper/v2/FreeBikeStatusFeedMapperTest.java

This PR maps a vehicle's `current_range_meters` as provided. A missing value is not set to a default of `0`, which would only be appropriate, if the vehicle_type's propulsion_type was not `human`. 
Closes #502
This PR updates `FreeBikeStatusFeedMapperTest.testMissingCurrentRangeMeters` to explicitly check, that missing `current_range_meters` is not filled in. While the test suggests an easy fix to just check the vehicle_type's propulsion_type by accessing it from `feedProvider.getVehicleTypes()`, this is usually not populated for harvested feeds, but would need explicit configuration.

Map current_range_meters as provided instead of setting a missing value to 0.0

---

pom.xml
src/main/java/org/entur/lamassu/leader/FeedUpdater.java
src/main/java/org/entur/lamassu/leader/LoggingSubscriptionUpdateInterceptor.java
src/main/resources/logback.xml

The gbfs-loader library has some useful logging, but lack context of feedprovider / system. This PR adds an interceptor to subscriptions so systemId can be added to mapped diagnostics context (mdc).
Depends on https://github.com/entur/gbfs-loader-java/pull/179
Closes #250. #514 should still be considered as a way to improve handling of those exceptions that are not caught in the library?

Add subscription update interceptor to add systemId to update logs

---

pom.xml
src/main/java/org/entur/lamassu/controller/GraphQLQueryController.java
src/main/java/org/entur/lamassu/service/BoundingBoxQueryParameters.java
src/main/java/org/entur/lamassu/service/FilterParameters.java
src/main/java/org/entur/lamassu/service/GeoSearchService.java
src/main/java/org/entur/lamassu/service/RangeQueryParameters.java
src/main/java/org/entur/lamassu/service/impl/GeoSearchServiceImpl.java
src/main/java/org/entur/lamassu/service/impl/GeoUtils.java
src/main/resources/graphql/schema.graphqls
src/test/java/org/entur/lamassu/integration/GraphQLIntegrationTest.java
src/test/resources/stations_bbox_query.graphql
src/test/resources/vehicles_bbox_query.graphql

This PR adds bounding box search functionality to vehicles and stations queries.
It should be noted that this method is *not* quicker than using radius, because the implementation must first do the radius search and do post-filtering. There is also some overhead in calculating the circle.
Closes #525 
Added integrationt tests
Documentation added to graphql schema. geometric functionality documented in code

Add bounding box search functionality to vehicles and stations queries

---

src/main/java/org/entur/lamassu/leader/entityupdater/StationsUpdater.java

This PR adds `org.entur.lamassu.stationEntityCacheMinimumTtl` and `org.entur.lamassu.stationEntityCacheMaximumTtl` configuration parameters. 
Closes #537
No unit tests added.
Cache related config params are added as comments to application.properties with their default values.

Improve: introduce configurable stationEntityCacheMinimumTtl and stationEntityCacheMaximumTtl

---

src/main/java/org/entur/lamassu/leader/FeedUpdater.java

With this PR, a feed update (i.e. caching the feeds) is performed immediately after successful subscription. 
That way, feeds will be available not only after `org.entur.lamassu.feedupdateinterval`, which e.g. for test instances, could be very high. 
Closes #581. 
Write a few words on how the new code is tested.
No tests were added/updated. All existing, enabled tests passed.

Update subscription immediately after registration

---

src/main/java/org/entur/lamassu/graphql/resolver/vehicletype/VehicleTypePricingPlanResolver.java

#596 introduced an NPE possibility if trying to resolve pricing plans but the ids were null. This fields are actually optional in the graphql schema, so it's not a breaking change.

Add null checks to avoid NPE

---

src/main/java/org/entur/lamassu/cache/EntityCache.java
src/main/java/org/entur/lamassu/cache/EntityReader.java
src/main/java/org/entur/lamassu/cache/RequestScopedCache.java
src/main/java/org/entur/lamassu/cache/RequestScopedEntityReader.java
src/main/java/org/entur/lamassu/config/cache/RequestScopedCacheConfig.java
src/main/java/org/entur/lamassu/graphql/query/GeofencingZonesQueryController.java
src/main/java/org/entur/lamassu/graphql/query/StationQueryController.java
src/main/java/org/entur/lamassu/graphql/query/VehicleQueryController.java
src/main/java/org/entur/lamassu/graphql/resolver/station/StationPricingPlanResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/station/StationRegionResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/station/StationSystemResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/station/StationVehicleTypeResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/vehicle/VehiclePricingPlanResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/vehicle/VehicleSystemResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/vehicle/VehicleTypeResolver.java
src/main/java/org/entur/lamassu/graphql/resolver/vehicletype/VehicleTypePricingPlanResolver.java

Adds request scoped caching of entity lookups - should remedy some of the performance hit in graphql 
queries introduced by #596. This also involves adding a separate interface for reading entities from the cache "EntityReader". 
Improves query performance by an order of magnitude in initial testing
#614

Add request-scope cache for reading entities

---

pom.xml

Problem described here #155 has become more prevalent in changes introduced in #619 and #543. Since we don't use devtools actively in this project, we might as well just remove it entirely from the dependencies.
Closes #155

fix: remove spring devtools, not used, and causes problems due to kryo

---

src/main/java/org/entur/lamassu/leader/entityupdater/VehicleFilter.java
src/test/java/org/entur/lamassu/leader/entityupdater/VehicleFilterTest.java

The vehicle filter's behavior to filter out vehicles that are assigned to a station, is founded on the assumption that users need to interact with the station's infrastructure in order to rent it. This did not account for virtual stations, which don't have physical infrastructure. This PR narrows down the filtering, so only vehicles that are assigned to a non-virtual station are filtered out.
In addition, configuration is added to opt-out of this filtering behavior.

Only filter out vehicles that are assigned to non-virtual stations

---

pom.xml

Upgrades base image / java version for jib to 21.0.5_11. For some reason, renovate doesn't pick this up.

Upgrade base docker image (java version)

---

src/main/java/org/entur/lamassu/service/impl/FeedProviderServiceImpl.java

A recent regression causes duplicate codespaces to be returned by the codespaces query. This PR fixes it.
Closes #622

Dedupe codespaces list

---

src/main/java/org/entur/lamassu/cache/impl/EntityCacheImpl.java

Recent refactoring introduced a regression in removal of entities in the cache. Currently, no entities are removed because of this error: instead of an error of keys we send Set#toString.
The result of this is that entities are never removed but build up over time.

Fixes remove entities from cache after refactoring

---

src/main/java/org/entur/lamassu/leader/entityupdater/VehicleFilter.java
src/test/java/org/entur/lamassu/leader/entityupdater/VehicleFilterTest.java

This PR, in `VehicleFilter`, treats a missing `is_virtual_station` as having a default of `false`.
Fixes #655
Added unit test to demonstrate the issue and fix.
No.
Done.
No.

Fix: in VehicleFilter, support is_virtual_station being optional

---

Changelog.md
docker-compose/application-config/application.properties
src/main/resources/application.properties

This PR updates two `application.properties` config param names and adds a note to the Changelog to make these config changes explicit.
fixes #657 
None
Added notes to existing changelog (that's why I added `skip changelog`  to this PR).

Fix: app config renamings [skip changelog]

---

src/main/java/org/entur/lamassu/leader/LeaderSingletonService.java
src/main/java/org/entur/lamassu/metrics/MetricUpdater.java
src/main/java/org/entur/lamassu/metrics/MetricsService.java
src/test/java/org/entur/lamassu/leader/LeaderSingletonServiceTest.java
src/test/java/org/entur/lamassu/metrics/MetricsUpdaterTest.java

This PR adds a metric `app.lamassu.gbfs.filesoverdue` which reports the number of overdue files per feedProvider.
A file is counted as overdue if
* `lastUpdated` + `ttl` + `${org.entur.lamassu.max-tolerated-overdue-seconds:120}` < `currentSecondsSinceEpoch` and
* it is not the gbfs.json file (this is currently only reloaded on lamassu startup)
Closes #341 
Added a unit test `MetricsUpdaterTest`.
No documentation.

feat: add metric for outdated feeds

---

src/main/java/org/entur/lamassu/leader/FeedUpdater.java
src/test/java/org/entur/lamassu/integration/AdminControllerIntegrationTest.java
src/test/java/org/entur/lamassu/leader/FeedUpdaterSubscriptionTest.java

In #679 I introduced the ability to control the lifecycle of subscriptions. However, when stopping a subscription, it also
sets the enabled status to false, which filters out the system from system discovery, but leaves any data intact.
Stopping a subscription should leave the system enabled. Only explicitly disabling should remove data and remove system from system discovery.

Do change enabled status when stopping a subscription

---

src/main/java/org/entur/lamassu/cache/CacheManagementService.java
src/main/java/org/entur/lamassu/cache/impl/CacheManagementServiceImpl.java
src/main/java/org/entur/lamassu/config/feedprovider/FeedProviderConfigRedis.java
src/main/java/org/entur/lamassu/controller/AdminController.java
src/test/java/org/entur/lamassu/integration/AdminControllerIntegrationTest.java

Protects feed provider config in redis when clearing old cache keys.
Also refactors AdminController so it must manage the cache via a service instead of using redisson client directly.
Closes #696

Protect feed provider config from cache clearing

---

src/main/java/org/entur/lamassu/mapper/feedmapper/GbfsFeedVersionMappers.java

Enables mapping v2 system_hours.json to v3 opening_hours field in system_information.json. See https://github.com/entur/gbfs-mapper-java/pull/94

Enable system hours to opening hours mapping
